### PR TITLE
Adding timeout to clear the search field

### LINKED ISSUE #182: Search returns alphabetically sorted list after clicking on a search result
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug

After typing something in the search bar and clicking on a search result, an alphabetically sorted list appears for a split second before resuming with the click action

### To Reproduce
1. Go to System Settings
2. Type something and click on a search result
3. See bug

### Expected behavior
The click should be instantaneous and the action of the click should follow without that list.

### Screenshots or screen recordings

system-settings

## Platform Information

image

Please check what applies:
-->
- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context
I reinstalled elementaryOS today after an OS wipe and just noticed this error. I was on Hera 5.1.4 earlier and this error wasn't occurring back then. Of course, I was using kernel 5.3.0-37-generic earlier and now it is 5.3.0-62-generic.

### PR DESCRIPTION
**Pull request by alainm23**
Fixed #182

### CODE REVIEW

**Review by danirabbit — CHANGES_REQUESTED** [review]
This also happens if you use the `clear` button. So maybe what would be better would be to add the timeout in the search changed handler before we call `invalidate_filter`?

**Comment by danirabbit** [comment]
Also don't forget to update metainfo with the bugfix line please :)

**Comment by alainm23** [comment]
I found a better way to fix it.

**Review by danirabbit — APPROVED** [review]
Clean! love not having to rely on a timeout too. Good job

**Pull request merged**
