### PR TITLE
Save and restore last-opened plug

### LINKED ISSUE #101: Save open plug state
After a discussion with @danrabbit, we concluded that System Settings was unique in that closing the window is not like minimizing, where the state is saved. Even if users may have a more linear flow with system settings, being able to open it and tweak a setting, close it to try the setting out, and re-open to further modify would be more consistent with how other apps work on elementary OS.

The main question I have is: how should this be implemented technically? My first instinct is to save the opened plug, but some plugs have multiple tabs and ideally we'd save that state as well. Would somehow saving the settings URI be possible, then we could use that when opening System Settings itself (without passing in a settings URI) to navigate back to that plug/subpage?

Ideally the following will all work:

- Opening System Settings from the .desktop will restore the plug and tab that was previously open

- Opening a specific plug/tab from Applications Menu search will still work and override the saved state

- Opening a specific `settings://foo/bar` URL will similarly still navigate to the correct plug/tab, overriding the saved state

- Opening `settings://` without any further path will open the main screen instead of the saved state

### PR DESCRIPTION
**Pull request by cassidyjames**
Fixes #101 

- [x] Add GSetting
- [x] Save state
- [x] Restore state

I'm not 100% this is the right way to do it, but it seems to work correctly. Opening from a settings:// link (i.e. Network settings from the indicator) correctly overrides and rewrites the state.

Notes:
- Bumped AppData release version to a minor release since this is a new feature
- Fixed indentation in GSchema
- Renamed settings vars to `saved_state` and `preferences` to better distinguish them

### CODE REVIEW

**Comment by danrabbit** [comment]
I've been testing this and I think I'm firmly :-1: on this.

My major problem with it is that System Settings is nearly always a linear workflow. I open something and then I'm done with it and the next time I open it, I almost certainly want to navigate somewhere completely different.

So what ends up happening is that I spend extra time navigating back home before I get to go to the place I want.

Maybe some kind of middle ground could be a timeout where we restore settings within the last 5 minutes (or something really tight like that) or at most in the same session? This would probably cover the case where you've changed something and then decided to immediately go back and change it again, but would be less likely to interrupt the case where you're navigating to a completely different setting.

I'd be interested in some user research to the contrary, but my inclination is that people don't typically change the same settings multiple times unless it's over a very short period of time or a very long period of time (in which case remembering the last used pane doesn't really help anyways)

**Comment by cassidyjames** [comment]
@danrabbit hm, remembering a timestamp of last-closed and then only restoring if it's been less than an amount of time should be pretty trivial. I can give that a try with a short span of a few minutes.

**Comment by cassidyjames** [comment]
@danrabbit alright, I've revisited this with a short one minute timeout. So if you're poking around at a setting, close Switchboard, and re-open within a minute, you get back to where you were. Otherwise, it retains the same behavior as today.

**Comment by cassidyjames** [comment]
Okay, something I noticed while testing: it doesn't remember the sub-section you were on, which is annoying. I wonder if I can do something similar to your search results branch where it restores using the settings URL, though I don't think we have a way to know and save that in every plug… hrm.

**Comment by jeremypw** [comment]
I think having a (arbitrary) timeout introduces an element of unpredictability so I am -1 on that. In general you can keep the Settings window open if you are making a series of changes as they usually are applied straight away (or should be).

**Comment by jeremypw** [comment]
Doesn't look like this is going anywhere ... 2 :-1: so far.

**Pull request closed without merging**
