### PR TITLE
Use Hdy.Deck for navigation

### LINKED ISSUE #2: Two-finger Forward/Back gestures
It should be possible to go forward and back by using a two-finger horizontal swipe gesture.

This is freaking awesome in Safari on Lion. Check it out: http://www.youtube.com/watch?v=KlBmWgvee-M

Bonus points for 1:1 finger tracking and an animation.

Massive bonus points for doing this in a way that we can easily copy to other apps.

Launchpad Details: [#LP1006115](https://bugs.launchpad.net/bugs/1006115) Daniel Fore - 2012-05-29 20:45:48 +0000

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/44032438-two-finger-forward-back-gestures?utm_campaign=plugin&utm_content=tracker%2F59959046&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F59959046&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by danrabbit**
Fixes #2

### CODE REVIEW

**Comment by Exalm** [comment]
> Looks like we need to wait for a newer version of Handy that exposes some more internals here

Hmm?

**Comment by danrabbit** [comment]
@Exalm you can ignore that. I was mistaken about the whole valac compiler error thing

**Comment by Exalm** [comment]
From the video on twitter I see you don't update the titlebar when doing a swipe. You're supposed to listen to `visible-child` and/or `transition-running` changes for that, instead of doing it on the back button press.

**Comment by danrabbit** [comment]
Yup. I’m rewriting a lot of how that’s handled currently in preparation for this

**Comment by Exalm** [comment]
I see you're just listening to `visible-child` and remove children after it changes. Don't do this, it really only works by accident, and will stop working after https://gitlab.gnome.org/GNOME/libhandy/-/issues/260 is fixed (we'll have new API, something like `page-shown` and `page-hidden` signals maybe.

**Comment by danrabbit** [comment]
Yeah I’ve realized that visible child changes as soon as a swipe begins so this causes issues if a swipe is canceled

**Comment by Exalm** [comment]
It actually changes back after you cancel it. But doing anything else with here would break the semantics, e.g. you change `visible-child` and it animates and only then actually changes `visible-child` value - that would be more weird.

So instead we'll just have another API, tentatively `signal void child-visible-changed (Gtk.Widget child, bool visible)`.

* You start transition from A to B, `child-visible-changed (B, true)` is emitted
* If you cancel it, `child-visible-changed (B, false)` is emitted
* If you finish it, `child-visible-changed (A, true)` is emitted

So that way you remove B on `child-visible-changed (B, false)`

**Pull request closed without merging**
