### PR TITLE
Responsive

### PR DESCRIPTION
**Pull request by danrabbit**
Screenshot from 2022-06-15 14 47 12
Screenshot from 2022-06-15 14 47 07
Screenshot from 2022-06-15 14 47 02

Todo:
- [x] https://github.com/elementary/switchboard/pull/238
- [x] Move plug labels?
- [x] https://github.com/elementary/switchboard/pull/237
- [x] https://github.com/elementary/switchboard/pull/239

### CODE REVIEW

**Review by jeremypw — CHANGES_REQUESTED** [review]
When the app first opens the window is resizable to a very small size however, when a plug is opened the window then enlarges to a size dependent on which plug it is. On returning to the category view, the window cannot be shrunk below the size of that plug.

Not sure of the utility of being able to shrink category view to a size smaller than required by the largest plug (we may have to re-engineer plugs to shrink better) and it is not satisfactory for the window size to change during use.

**Comment by danrabbit** [comment]
Yeah there will need to be work done on all of the plugs to make them responsive as well.

I'm afk currently but there may be a setting for Adw.Deck to make sure we aren't enforcing it to be homogeneous, but it might not have any effect because the plug doesn't get destroyed until we navigate forward to a new plug (which enables us to swipe forward).

**Review by jeremypw — APPROVED** [review]
On the basis that all the plugs are going to be made responsive as well before any release, there is no harm in merging this into `main`.

**Comment by danrabbit** [comment]
`main` is also the Gtk4 branch, so plenty of time to fix things up as well :)

**Pull request merged**
