### PR TITLE
CategoryView: absorb headerbar

### PR DESCRIPTION
**Pull request by danirabbit**
Follow up to #278 as part of my evil plan to flatten settings. Plugins will now be responsible for providing window controls and a back button

Window controls in each plugin:
- [x] https://github.com/elementary/switchboard-plug-useraccounts/pull/223
- [x] https://github.com/elementary/switchboard-plug-printers/pull/202
- [x] https://github.com/elementary/switchboard-plug-network/pull/396
- [x] https://github.com/elementary/switchboard-plug-locale/pull/188
- [x] https://github.com/elementary/switchboard-plug-notifications/pull/100
- [x] https://github.com/elementary/switchboard-plug-parental-controls/pull/191
- [x] https://github.com/elementary/switchboard-plug-applications/pull/214
- [x] https://github.com/elementary/switchboard-plug-pantheon-shell/pull/389
- [x] https://github.com/elementary/switchboard-plug-security-privacy/pull/173
- [x] https://github.com/elementary/switchboard-plug-display/pull/380
- [x] https://github.com/elementary/switchboard-plug-keyboard/pull/503
- [x] https://github.com/elementary/switchboard-plug-mouse-touchpad/pull/232
- [x] https://github.com/elementary/switchboard-plug-power/pull/263
- [x] https://github.com/elementary/switchboard-plug-sound/pull/268
- [x] https://github.com/elementary/switchboard-plug-bluetooth/pull/218
- [x] https://github.com/elementary/switchboard-plug-wacom/pull/63
- [x] https://github.com/elementary/switchboard-plug-onlineaccounts/pull/279
- [x] https://github.com/elementary/switchboard-plug-sharing/pull/71
- [x] https://github.com/elementary/switchboard-plug-datetime/pull/122
- [x] https://github.com/elementary/switchboard-plug-about/pull/314

### CODE REVIEW

**Review by leolost2605 — COMMENTED** [review]
Is it possible to get the window controls to the same height as on the setting pages etc.? IMHO it currently looks a bit "stretched" with them being quite far down :shrug:

**Comment by danirabbit** [comment]
@leolost2605 can you post a screenshot? It looks the same here

**Comment by leolost2605** [comment]
image
Compared to
image

**Comment by danirabbit** [comment]
@leolost2605 oh wow haha. Can you make sure you're on io.elementary.stylesheet 7.3.0+r524+pkg338~daily~ubuntu24.04.1?

**Review by leolost2605 — APPROVED** [review]
`ninja clean` fixed it, sorry 😬

But let's gooo 🎉

**Pull request merged**
